//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchConnection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ファイル保存の確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_close_title {
            get {
                return ResourceManager.GetString("str_close_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Studuinoプログラミング環境を再インストールして下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_emg_msg {
            get {
                return ResourceManager.GetString("str_emg_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムファイルが壊れています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_emg_title {
            get {
                return ResourceManager.GetString("str_emg_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非対応なデータです。選択し直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_err_file_open1 {
            get {
                return ResourceManager.GetString("str_err_file_open1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_file_name_new {
            get {
                return ResourceManager.GetString("str_file_name_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SENSOR A4/A5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_acc {
            get {
                return ResourceManager.GetString("str_lb_sns_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加速度センサー X に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_acc_x {
            get {
                return ResourceManager.GetString("str_lb_sns_acc_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加速度センサー Y に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_acc_y {
            get {
                return ResourceManager.GetString("str_lb_sns_acc_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加速度センサー Z に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_acc_z {
            get {
                return ResourceManager.GetString("str_lb_sns_acc_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_bt {
            get {
                return ResourceManager.GetString("str_lb_sns_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センサー未接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_not_connect {
            get {
                return ResourceManager.GetString("str_lb_sns_not_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SENSOR A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_sns_vw {
            get {
                return ResourceManager.GetString("str_lb_sns_vw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_val_sns_off {
            get {
                return ResourceManager.GetString("str_lb_val_sns_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_lb_val_sns_on {
            get {
                return ResourceManager.GetString("str_lb_val_sns_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了する前に変更を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_close {
            get {
                return ResourceManager.GetString("str_msg_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイブ時にエラーが発生しました。下記にメッセージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_archive {
            get {
                return ResourceManager.GetString("str_msg_err_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンパイルエラーが発生しました。下記にメッセージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_compile {
            get {
                return ResourceManager.GetString("str_msg_err_compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロボットとの接続が確認されませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_discon1 {
            get {
                return ResourceManager.GetString("str_msg_err_discon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】ロボットとPCがUSBケーブルで接続されているかどうか確かめてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_discon2 {
            get {
                return ResourceManager.GetString("str_msg_err_discon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロボットとの通信が切断されました。予期せずソフトウェアが終了する可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_discon3 {
            get {
                return ResourceManager.GetString("str_msg_err_discon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】ソフトウェアを終了します。プログラムを保存してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_discon4 {
            get {
                return ResourceManager.GetString("str_msg_err_discon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StuduinoとPCの同期が取れませんでした。
        ///このプロジェクトを保存し、プログラミング環境を終了し、
        ///Studuinoをリセットして、プログラミング環境を再度起動して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_discon5 {
            get {
                return ResourceManager.GetString("str_msg_err_discon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   センサーが指定されていない条件があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon1 {
            get {
                return ResourceManager.GetString("str_msg_err_icon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon2 {
            get {
                return ResourceManager.GetString("str_msg_err_icon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   のセンサー種類を設定してから、本処理を行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon3 {
            get {
                return ResourceManager.GetString("str_msg_err_icon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効な行動アイコンがあります。【No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon4 {
            get {
                return ResourceManager.GetString("str_msg_err_icon4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理を行いますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon5 {
            get {
                return ResourceManager.GetString("str_msg_err_icon5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_icon6 {
            get {
                return ResourceManager.GetString("str_msg_err_icon6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リンク時にエラーが発生しました。下記にメッセージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_link {
            get {
                return ResourceManager.GetString("str_msg_err_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロボットとの接続に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_miscon1 {
            get {
                return ResourceManager.GetString("str_msg_err_miscon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】ほかのアプリケーションがロボットと通信中です。通信をしている可能性のあるアプリケーションを終了して、再度接続してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_miscon2 {
            get {
                return ResourceManager.GetString("str_msg_err_miscon2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】ロボットとPCがUSBケーブルで接続されているかどうか確かめてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_miscon3 {
            get {
                return ResourceManager.GetString("str_msg_err_miscon3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロボットとの通信が確立できませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_noresp1 {
            get {
                return ResourceManager.GetString("str_msg_err_noresp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【対策】もう一度トライしても通信できない場合は、プログラムを保存してソフトウェアを再起動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_noresp2 {
            get {
                return ResourceManager.GetString("str_msg_err_noresp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オブジェクトコピー時にエラーが発生しました。下記にメッセージを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_objcopy {
            get {
                return ResourceManager.GetString("str_msg_err_objcopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Studuinoと通信できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_title1 {
            get {
                return ResourceManager.GetString("str_msg_err_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WMIサービスが停止している可能性があります。COMポートの自動取得が出来ないため、ダイアログから使用するCOMポートを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_err_wmi {
            get {
                return ResourceManager.GetString("str_msg_err_wmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のファイルを保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_file_save {
            get {
                return ResourceManager.GetString("str_msg_file_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リピートブロックが閉じられていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_msg_warn_repeat {
            get {
                return ResourceManager.GetString("str_msg_warn_repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンパイル中… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_compiling {
            get {
                return ResourceManager.GetString("str_note_compiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト・モード移行中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_mode_test_1 {
            get {
                return ResourceManager.GetString("str_note_mode_test_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基板と接続中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_mode_test_2 {
            get {
                return ResourceManager.GetString("str_note_mode_test_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テスト・モード移行完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_mode_test_3 {
            get {
                return ResourceManager.GetString("str_note_mode_test_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信更新処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_mode_upd1 {
            get {
                return ResourceManager.GetString("str_note_mode_upd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通信を更新中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_mode_upd2 {
            get {
                return ResourceManager.GetString("str_note_mode_upd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プログラム転送中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_transffering {
            get {
                return ResourceManager.GetString("str_note_transffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   基板に転送中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_note_updating {
            get {
                return ResourceManager.GetString("str_note_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アイコンプログラミング用ファイル(*.ipd)|*.ipd|すべてのファイル(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_ofd_filter {
            get {
                return ResourceManager.GetString("str_ofd_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開くファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_ofd_title {
            get {
                return ResourceManager.GetString("str_ofd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_button {
            get {
                return ResourceManager.GetString("str_parts_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_button1 {
            get {
                return ResourceManager.GetString("str_parts_button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_button2 {
            get {
                return ResourceManager.GetString("str_parts_button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_button3 {
            get {
                return ResourceManager.GetString("str_parts_button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタン4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_button4 {
            get {
                return ResourceManager.GetString("str_parts_button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_dev_buzzer {
            get {
                return ResourceManager.GetString("str_parts_dev_buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カラーLED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_dev_colorLed {
            get {
                return ResourceManager.GetString("str_parts_dev_colorLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_dev_led {
            get {
                return ResourceManager.GetString("str_parts_dev_led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   加速度センサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_sensor_acc {
            get {
                return ResourceManager.GetString("str_parts_sensor_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   赤外線フォトリフレクタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_sensor_ir {
            get {
                return ResourceManager.GetString("str_parts_sensor_ir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   光センサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_sensor_light {
            get {
                return ResourceManager.GetString("str_parts_sensor_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音センサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_sensor_sound {
            get {
                return ResourceManager.GetString("str_parts_sensor_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タッチセンサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_parts_sensor_touch {
            get {
                return ResourceManager.GetString("str_parts_sensor_touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // 加速度センサ開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_acc {
            get {
                return ResourceManager.GetString("str_scr_comment_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // ボタン入力の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_bt {
            get {
                return ResourceManager.GetString("str_scr_comment_bt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // ブザー設定処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_buzzer {
            get {
                return ResourceManager.GetString("str_scr_comment_buzzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // DCモータの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_dc {
            get {
                return ResourceManager.GetString("str_scr_comment_dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // モーターをプルアップする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_dc_pullup {
            get {
                return ResourceManager.GetString("str_scr_comment_dc_pullup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // DCモータ1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_dc1 {
            get {
                return ResourceManager.GetString("str_scr_comment_dc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // DCモータ2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_dc2 {
            get {
                return ResourceManager.GetString("str_scr_comment_dc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // LED設定処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_led {
            get {
                return ResourceManager.GetString("str_scr_comment_led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // プルアップ処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_pullup {
            get {
                return ResourceManager.GetString("str_scr_comment_pullup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // センサ入力の設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_sns {
            get {
                return ResourceManager.GetString("str_scr_comment_sns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // サブメニュー1を実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_sub1_2 {
            get {
                return ResourceManager.GetString("str_scr_comment_sub1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // サブメニュー2を実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_sub2_2 {
            get {
                return ResourceManager.GetString("str_scr_comment_sub2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // サーボモータの設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_scr_comment_sv {
            get {
                return ResourceManager.GetString("str_scr_comment_sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいファイル.ipd に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_sfd_file_name {
            get {
                return ResourceManager.GetString("str_sfd_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存先のファイルを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_sfd_title {
            get {
                return ResourceManager.GetString("str_sfd_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Studuinoアイコンプログラミング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_software_name {
            get {
                return ResourceManager.GetString("str_software_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // サブメニュー1処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_comment_sub1_1 {
            get {
                return ResourceManager.GetString("str_src_comment_sub1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // サブメニュー2処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_comment_sub2_1 {
            get {
                return ResourceManager.GetString("str_src_comment_sub2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // プロトタイプ宣言 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_comment1 {
            get {
                return ResourceManager.GetString("str_src_comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // メニュー処理を実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_comment2 {
            get {
                return ResourceManager.GetString("str_src_comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // メニュー処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_comment3 {
            get {
                return ResourceManager.GetString("str_src_comment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arduino言語ソースコード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string str_src_title {
            get {
                return ResourceManager.GetString("str_src_title", resourceCulture);
            }
        }
    }
}
